version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:16.0
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5432:5432'
    networks:
      - network
volumes:
  db-data:
networks:
  network:
    driver: bridge