import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.scss"
import { Montserrat } from "next/font/google";
import { useCookies } from "react-cookie";
import { useContext, useEffect } from "react";
import { useRouter } from "next/navigation";
import { CookiesProvider } from 'react-cookie';

const roboto = Montserrat({
  weight: ["200", "300", "400", "500", "600", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div id="snackBar"></div>
        {children}
        </body>
    </html>
  )
}
